# Use the official Python 3.9 slim image as the base image
FROM python:3.9-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy 'requirements.txt' from the current directory on the host to the container
COPY requirements.txt .

# Install the Python dependencies specified in requirements.txt without caching
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . /app

# Expose port 5000 on the container to allow external access
EXPOSE 5000

# Define the command to run the application when the container starts
CMD ["python", "app.py"]
